name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue on PYSlots needs attention!'
        stale-pr-message: 'This PR on PYSlots needs attention!'
        stale-issue-label: 'stale-issue-pyslots'
        stale-pr-label: 'stale-pr-pyslots'
